[package]
name = "hello-world"
version = "0.1.0"
authors = ["Suman Kumar <skcool.123bgp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rift_lib = {path = "rift_lib"}